### ISSUE TITLE
No support for args

### ISSUE THREAD

**Issue by gienec** [Mikhus/graphql-fields-list#7]
No support for arguments e. g. `myField(id:1)`.

**Comment by Mikhus** [comment]
First of all, thank you very much for your contribution! BTW I have a couple of questions to be answered here to make this request to be better clarified.

Which reason to support args here? Could you please, provide a real world example when you need arguments been parsed and provided here? How you imagine it should support this? Which type of output you expect to have? I need more understanding on args here, because this library was built to provide a way to access attributes names, which was requested by the user's query to prevent under/over fetching of data from an underlying data-source. Maybe you trying to solve some task using this lib, which it was either not designed to do, or I misinterpret the meaning and it will be really required for some specific cases which I just can not imagine correctly. Thank you in advance.

**Comment by thomasreinecke** [comment]
Hi @Mikhus , I agree args support would be very helpful as your lib could support more complex mapping scenarios with e.g. relational databases or ORMs. 

example:
```
query {
  currency(symbol:"EUR", isoCode:978) {
    data {
      id
      symbol
      name
      isoCode
    }
  }
}
```
The field list/map can easily be used as the SELECT piece, the args list/map could be used to compose the WHERE piece of a SQL query and could be mapped into a RDMS as 
```select id, symbol, name, isoCode from currency where symbol="ABC" and isoCode=666```

the output expected here is simply either a list and/or map of the args in key/value pairs including nested requests for child objects.

**Comment by erming** [comment]
@thomasreinecke + @gienec:

Maybe you could use the `args` function argument from your resolvers? It's already provided by native graphql. I'm doing this in one of my projects, see example code:

```
query {
  currency(symbol: "EUR") {
    ...
  }
}

resolve(source, args, context, info) {
  console.log(args); // should return { "symbol": "EUR" }
}
```

Ping @Mikhus

**Comment by Mikhus** [comment]
Typically args are parsed and passed to graphql resolvers, so their structure seems to be well known during resolver implementation. Also, generic filtering model usually quite more complicated then "where something AND something". It may be or, not, in, etc... ways to build filtering part of the query is not that simple. Also it should take into account filtering on SQL joins, ordering and pagination. For example, we've built library of helpers for sequelize ORM for one of my mutual projects @imqueue/sequelize which provides query builder helpers, supporting complex filtering. Where filters are expected to be special structures passed as graphql arguments. Because when you working on a real world application filtering only by simple "where something AND something" usually is not enough. So, depending on this experience I see no simple way to map simple args to filtering SQL clauses. Yes, it can be done as you propose, but is to be very limited, non-generic solution. Generic solution requires some specific argument definitions and their logic, which, as for me, should be done separately from this library. I prefer this library does one exact thing - providing info about requested by user fields in a graphql query. Filtering part is another projects, especially if follow single responsibility principle.

**Comment by thelinuxlich** [comment]
I have a valid use case for this, in my Type:

```graphql
"""@model"""
type Todo {
  id: ID!
  a: Int
  b: Int
  c: Int

  """@transient"""
  count(of: OfTodoInput): Int

  """@transient"""
  avg(of: OfTodoInput): Int

  """@transient"""
  max(of: OfTodoInput): Int

  """@transient"""
  min(of: OfTodoInput): Int

  """@transient"""
  sum(of: OfTodoInput): Int
}
```
These "transient" fields won't appear in Mutations but will be valid to be returned on query projections
